os: unstable
environment:
  matrix:
  - nodejs_version: "6"

platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - ps: $env:Path += ";$(pwd)\node_modules\.bin";
  - ps: >
      @{
        "nodejs_version" = $env:nodejs_version
        "platform" = $env:platform
        "node binary version" = $(node -v)
        "node platform@arch" = $(node -p 'process.platform + process.arch')
        "npm version" = $(npm -v)
        "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
        "git latest tag" = "$(git describe --tags --always HEAD)"
        "appveyor_repo_tag" = $env:appveyor_repo_tag
      } | Out-String | Write-Host;

  # Cleanup the output of npm
  - ps: >
      npm config set progress false
      npm config set spin false

  # Install dependencies
  - npm install

build_script:
  - npm run compile

test_script:
  - npm run test

deploy: OFF

matrix:
  fast_finish: true
